version: '3.1'

services:
  db:
    image: postgres:13.5
    privileged: true
    restart: always
    ports:
      - "54325:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todo

  backend:
    build: ./first_project
    privileged: true
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: 'first_project.settings.prod'
    command: bash -c "
        python manage.py migrate &&
        gunicorn first_project.wsgi -b 0.0.0.0:8080
      "
  nginx:
    build: ./first_project/nginx
    privileged: true
    ports:
      - "8000:80"
    depends_on:
      - backend

  frontend:
    build: ./first_project/frontend
    privileged: true
    ports:
      - "80:80"
    depends_on:
      - backend
